In [1]:
import numpy as np

In [4]:
numbers = np.array([10, 20, 30, 40, 50])
numbers

array([10, 20, 30, 40, 50])

In [6]:
print("Array: ")
print(numbers)

print()

print("Shape:", numbers.shape)
print("size:", numbers.size)
print("Data type:", numbers.dtype)
print("Dimensions:", numbers.ndim)

Array: 
[10 20 30 40 50]

Shape: (5,)
size: 5
Data type: int64
Dimensions: 1


In [8]:
print("sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Max:", np.max(numbers))
print("standard devation:", np.std(numbers))

sum: 150
Mean: 30.0
Max: 50
standard devation: 14.142135623730951


In [12]:
matrix= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
matrix
print(matrix[0])


[1 2 3]


In [13]:
numbers.reshape(5,1)

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [14]:
numbers.reshape(1,5)

array([[10, 20, 30, 40, 50]])

In [16]:
random_numbers = np.random.randint(1, 100, size=10)
random_numbers

array([39, 63, 12, 19, 72, 12, 21, 64,  1, 53])